(deftheme bluer than blue
  "Created 2016-01-26.")

(custom-theme-set-variables
 'bluer than blue
 '(ansi-color-names-vector ["#212526" "#ff4b4b" "#b4fa70" "#fce94f" "#729fcf" "#e090d7" "#8cc4ff" "#eeeeec"])
 '(custom-safe-themes (quote ("bf25a2d5c2eddc36b2ee6fc0342201eb04ea090e637562c95b3b6e071216b524" "ff33345ae70aa73195aec978e6c07b4d7498dcde9072016bf1744a2e4387698d" "b128be65cf2a018966ff27cbaa126876baee152a3fd48c898050263d54e64c49" "e80240136337af0c3fba2649f4cda267ebb1368412373e34361c9be768d3e416" "e0c3ef2750b8556c0a2853ee2d0824e8e5baebaa86e4648fc6a3d653953a1922" default)))
 '(display-battery-mode t)
 '(aquamacs-additional-fontsets nil)
 '(aquamacs-customization-version-id 307)
 '(aquamacs-tool-bar-user-customization nil)
 '(default-frame-alist (quote ((alpha 100 85) (left . 0) (width . 141) (height . 44))))
 '(ns-tool-bar-display-mode (quote both))
 '(ns-tool-bar-size-mode nil)
 '(visual-line-mode nil)
 '(global-hl-line-mode t)
 '(global-linum-mode t))

(custom-theme-set-faces
 'bluer than blue
 '(special-mode-default ((t (:inherit autoface-default))))
 '(messages-buffer-mode-default ((t (:inherit special-mode-default))))
 '(default ((t (:inherit nil :stipple nil :background "Black" :foreground "#92cce3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Hack"))))
 '(dired-directory ((t (:foreground "#14efff"))))
 '(dired-header ((t (:foreground "#83c3a2"))))
 '(enh-ruby-op-face ((t (:foreground "#98dfee"))))
 '(enh-ruby-string-delimiter-face ((t (:foreground "#98dfee"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7fd48c"))))
 '(font-lock-comment-face ((t (:foreground "#7fd48e" :slant italic))))
 '(font-lock-constant-face ((t (:background "#000000" :foreground "#6dab9f" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#8edced" :slant italic :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#6175d7" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#97a7d7" :slant italic))))
 '(font-lock-type-face ((t (:foreground "#84a5d8" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#7eabed" :slant italic :weight bold))))
 '(helm-ff-directory ((t (:background "#1c2533" :foreground "#5f779d"))))
 '(helm-ff-dotted-directory ((t (:background "#4b6e81" :foreground "#8bc9e8"))))
 '(helm-selection ((t (:background "#87ccd1" :foreground "#243e3b"))))
 '(ruby-mode-default ((t (:inherit prog-mode-default :height 160 :family "Anonymous Pro"))))
 '(sass-mode-default ((t (:inherit haml-mode-default :height 180 :family "Anonymous Pro"))))
 '(css-mode-default ((t (:inherit autoface-default))))
 '(prog-mode-default ((t (:inherit autoface-default))))
 '(web-mode-prog-mode-default ((t (:inherit autoface-default))))
 '(web-mode-default ((t (:inherit web-mode-prog-mode-default :height 150 :family "Consolas"))))
 '(scss-mode-default ((t (:inherit css-mode-default :height 140 :family "Monaco"))))
 '(enh-ruby-parent-mode-default ((t (:inherit autoface-default))))
 '(yaml-mode-default ((t (:inherit autoface-default :height 160 :family "Anonymous Pro"))))
 '(coffee-mode-default ((t (:inherit prog-mode-default :height 160 :family "Anonymous Pro"))))
 '(diff-mode-default ((t (:inherit autoface-default))))
 '(helm-grep-mode-default ((t (:inherit special-mode-default))))
 '(enh-ruby-mode-default ((t (:inherit enh-ruby-parent-mode-default :stipple nil :background "#000000" :foreground "#cecece" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 160 :width normal :foundry "nil" :family "Anonymous Pro"))))
 '(js-mode-default ((t (:inherit prog-mode-default :height 160 :family "Anonymous Pro"))))
 '(text-mode-default ((t (:inherit autoface-default :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 130 :width normal :family "Lucida Grande"))))
 '(conf-mode-default ((t (:inherit autoface-default))))
 '(conf-unix-mode-default ((t (:inherit conf-mode-default))))
 '(conf-space-mode-default ((t (:inherit conf-unix-mode-default))))
 '(dired-mode-default ((t (:inherit autoface-default :height 180 :family "Anonymous Pro"))))
 '(minibuffer-inactive-mode-default ((t (:inherit autoface-default))))
 '(custom-theme-choose-mode-default ((t (:inherit special-mode-default))))
 '(fundamental-mode-default ((t (:inherit autoface-default))))
 '(emacs-lisp-mode-default ((t (:inherit prog-mode-default :height 150 :family "Anonymous Pro"))))
 '(custom-new-theme-mode-default ((t (:inherit autoface-default)))))

(provide-theme 'bluer than blue)
